-- USERS
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255)
);

-- CHILDREN
CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    first_name VARCHAR(255),
    birthday DATE,
    gender VARCHAR(50),
    avatar VARCHAR(255),
    CONSTRAINT fk_child_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- EVENTS
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL,
    child_id BIGINT NOT NULL,
    datetime TIMESTAMP,
    location_type VARCHAR(50),
    location VARCHAR(500),
    status VARCHAR(50),
    comment VARCHAR(500),
    CONSTRAINT fk_event_host FOREIGN KEY (host_id) REFERENCES users(id),
    CONSTRAINT fk_event_child FOREIGN KEY (child_id) REFERENCES children(id)
);

-- EVENT GUESTS
CREATE TABLE event_guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    guest_name VARCHAR(255),
    user_id BIGINT,
    rsvp_status VARCHAR(50),
    CONSTRAINT fk_event_guest_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_event_guest_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- GUEST TOKENS
CREATE TABLE guest_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id BIGINT NOT NULL,
    token VARCHAR(255) UNIQUE,
    valid_until TIMESTAMP,
    CONSTRAINT fk_guest_token FOREIGN KEY (guest_id) REFERENCES event_guests(id)
);

-- GIFTS
CREATE TABLE gifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    title VARCHAR(255),
    description VARCHAR(500),
    url VARCHAR(500),
    image VARCHAR(500),
    price DECIMAL(10,2),
    status VARCHAR(50),
    reserved_by_guest BIGINT,
    CONSTRAINT fk_gift_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_gift_guest FOREIGN KEY (reserved_by_guest) REFERENCES event_guests(id)
);

-- PROVIDERS
CREATE TABLE providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255),
    website VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    address VARCHAR(255),
    description VARCHAR(1000)
);

-- CHAT MESSAGES
CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT,
    message VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(id)
);
