-- GUEST CHILDREN
-- Таблица для хранения детей гостей события (минимальные данные - только имя)
CREATE TABLE guest_children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id BIGINT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_guest_child_guest FOREIGN KEY (guest_id) REFERENCES event_guests(id) ON DELETE CASCADE
);
