-- GIFT CATEGORIES
-- Таблица категорий подарков
CREATE TABLE gift_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Связь many-to-many между подарками и категориями
CREATE TABLE gift_category_mapping (
    gift_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (gift_id, category_id),
    CONSTRAINT fk_gift_category_gift FOREIGN KEY (gift_id) REFERENCES gifts(id) ON DELETE CASCADE,
    CONSTRAINT fk_gift_category_category FOREIGN KEY (category_id) REFERENCES gift_categories(id) ON DELETE CASCADE
);

-- Создаем категории
INSERT INTO gift_categories (name) VALUES
    ('Lego'),
    ('Sport'),
    ('Outdoor'),
    ('Bücher'),
    ('Basteln');

-- Связываем существующие подарки с категориями
-- Подарок 1 (LEGO Technic Set) -> категория "Lego"
INSERT INTO gift_category_mapping (gift_id, category_id)
SELECT 1, id FROM gift_categories WHERE name = 'Lego';

-- Подарок 2 (Fußball) -> категории "Sport" и "Outdoor"
INSERT INTO gift_category_mapping (gift_id, category_id)
SELECT 2, id FROM gift_categories WHERE name = 'Sport'
UNION ALL
SELECT 2, id FROM gift_categories WHERE name = 'Outdoor';

-- Подарок 3 (Bücherpaket) -> категория "Bücher"
INSERT INTO gift_category_mapping (gift_id, category_id)
SELECT 3, id FROM gift_categories WHERE name = 'Bücher';
