-- Рефакторинг: выносим avatar в отдельную таблицу
-- Создаем таблицу user_avatars
CREATE TABLE user_avatars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    avatar CLOB NOT NULL,
    CONSTRAINT fk_user_avatar_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Переносим данные из users.avatar в user_avatars
INSERT INTO user_avatars (user_id, avatar)
SELECT id, avatar
FROM users
WHERE avatar IS NOT NULL AND avatar != '';

-- Удаляем колонку avatar из таблицы users
ALTER TABLE users DROP COLUMN avatar;
