-- Рефакторинг: выносим avatar в отдельную таблицу для детей
-- Создаем таблицу child_avatars
CREATE TABLE child_avatars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT NOT NULL UNIQUE,
    avatar CLOB NOT NULL,
    CONSTRAINT fk_child_avatar_child FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE
);

-- Переносим данные из children.avatar в child_avatars
-- Обрабатываем только непустые значения
INSERT INTO child_avatars (child_id, avatar)
SELECT id, avatar
FROM children
WHERE avatar IS NOT NULL AND avatar != '';

-- Удаляем колонку avatar из таблицы children
ALTER TABLE children DROP COLUMN avatar;
